# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
---
name: gh-pages

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:

jobs:

  run:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      conclusion: ${{ steps.url-action.conclusion }}
    steps:
      - id: url-action
      # Comment following line only for first upload (if needed)
        uses: rzr/url-action@main
      - id: output
        run: |
          echo "warning: Please pin above use to latest release:"
          echo "info: https://github.com/rzr/url-action/releases"
          echo "conclusion=$(echo ${{ steps.url-action.conclusion }})" >> $GITHUB_ENV

  bypassed:
    runs-on: ubuntu-latest
    needs: run
    if: ${{ needs.run.outputs.conclusion != 'success' }}
    steps:
      - run: |
          echo "log: conclusion=${{ needs.run.outputs.conclusion }}"
          echo "log: result=${{ needs.run.result }}"
          echo "log: is there a better way to trap and forward error code?"

  upload:
    runs-on: ubuntu-latest
    needs: run
    if: ${{ needs.run.outputs.conclusion == 'success' }}
    steps:
      - id: build
        run: install -d _site && touch _site/index.html
      - id: upload
        uses: actions/upload-pages-artifact@v3.0.1

  deploy:
    needs: upload
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: upload
        uses: actions/deploy-pages@v4.0.5
